version: "3"
services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    container_name: mybackend
    ports:
      - "8005:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  ml:
    build:
      context: ./ml
    container_name: ml
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    container_name: campusx-nginx
    volumes:
      - ./frontend/dist:/usr/share/nginx/html # Serve frontend build
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Custom nginx config
    ports:
      - "80:80"
    depends_on:
      - backend
      - ml
